### ISSUE TITLE
Github API rate limit

### ISSUE THREAD

**Issue by TheQwertiest** [3dyd/acfu#8]
Check for updates through `foo_acfu` sometimes fails with the following message:

> `component_name`: API rate limit exceeded for `IP.address`. (But here's the good news: Authenticated requests get a higher rate limit. Check out the documentation for more details.)`

Would it be possible to add Github API token setting in `Preferences`>`Advanced` section to workaround this problem? (similar to YT API token in `foo_youtube`)

**Comment by 3dyd** [comment]
Done. Note, since checking for updates actually goes on your side, your component(s) need to be compiled with updated SDK 0.3 to make use of this feature.

**Comment by TheQwertiest** [comment]
Thanks!
